# Site settings
title: Pawels software and stuff
email: p.k.burzynski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog where I write about software development and other stuff that is technology related.
  There are many blogs like this but this one is mine.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://burzyk.github.io" # the base hostname & protocol for your site
twitter_username: pburzynski
github_username:  burzyk

# Build settings
markdown: kramdown
